:toc:
:source-highlighter: highlightjs
:toclevels: 2
:toc-title: Table of contents

:xrefstyle: short
:section-refsig:

= Test robot

== Mainboard

link:https://github.com/ReikoR/pwir21-NUCLEO-adapter[Altium Designer project]

link:https://github.com/ReikoR/pwir21-NUCLEO-adapter/blob/master/pwir21-NUCLEO-adapter-panel.PDF[Schematic and PCB drawing PDF]

=== NUCLEO modifications

There are jumper resistors and solder pads on the NUCLEO board that are used to connect some microcontroller pins to pin headers.
Firmware uses some pins differently from the default jumper configuration.
Necessary modifications are shown in <<image_nucleo_jumpers>>.
0 ohm resistors marked as SB2 and SB3 should be removed and jumper pads marked as 8 and 11 should be soldered together.
Alternatively SB2 and SB3 resistors can be soldered onto jumper pads 8 and 11.

[#image_nucleo_jumpers]
.NUCLEO jumper modifications
image::../images/test_robot_nucleo_jumper_modifications.svg[width=300]

=== Firmware

==== Binary firmware file

link:https://github.com/ReikoR/picr21-basketball-robot-guide/raw/master/source/electronics/picr21-NUCLEO-adapter-firmware.bin[picr21-NUCLEO-adapter-firmware.bin]

Connect NUCLEO to a computer and drag or copy the *.bin file on the NOD_G431KB drive.

==== Sending commands to mainboard

Struct in firmware

[source,c,tabsize=2]
----
typedef struct Command {
  int16_t speed1;
  int16_t speed2;
  int16_t speed3;
  uint16_t throwerSpeed;
  uint16_t delimiter;
} Command;
----

Using with python's link:https://docs.python.org/3/library/struct.html[struct library]

[source,python,tabsize=4]
----
struct.pack('<hhhHH', speed1, speed2, speed3, thrower_speed, 0xAAAA)
----

==== Receiving data from mainboard

Struct in firmware

[source,c,tabsize=2]
----
typedef struct Feedback {
  int16_t speed1;
  int16_t speed2;
  int16_t speed3;
  uint16_t delimiter;
} Feedback;
----

Using with python's link:https://docs.python.org/3/library/struct.html[struct library]

[source,python,tabsize=4]
----
actual_speed1, actual_speed2, actual_speed3, feedback_delimiter = struct.unpack('<hhhH', received_data)
----

== Wheel motor driver

link:https://digilabor.ut.ee/index.php/MC33886_driver_board[Wiki page]

link:https://github.com/ReikoR/MC33886_driver_board[Altium Designer project]

link:https://github.com/ReikoR/MC33886_driver_board/blob/master/MC33886_driver_board.PDF[Schematic PDF]

